plugins:
  - jest
env:
  es2021: true
  node: true
  jest/globals: true
extends:
  - airbnb-base
  - prettier
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  import/extensions: 0
  no-console: 0
