plugins:
  - jest
env:
  es2021: true
  node: true
  jest/globals: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
  sourceType: module
  requireConfigFile: false
rules:
  import/extensions: 0
  no-console: 0
parser: "@babel/eslint-parser"
